version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3-stretch
  working_directory: ~/build-root

jobs:
  clone_and_hash:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Initialize metadata
          command: |
            virtualenv blaenv
            blaenv/bin/pip install requests
            blaenv/bin/python .circleci/find_changed_projects.py

      - persist_to_workspace:
          root: .
          paths:
            - .
  client:
    <<: *defaults
    working_directory: ~/build-root/client
    steps:
      - attach_workspace: { at: ~/build-root }
      - run:
          name: Check whether client changed
          command: |
            if [ -e ci_meta/not_changed ]; then
              if [ -e ci_meta/success ]; then
                exit 0
              else
                exit 1
              fi
            else
              echo "run tests"
            fi

      - run:
          name: Install dependencies
          command: echo "install"

      - run:
          name: Build
          command: echo "Building Client"

      - run:
          name: Test
          command: ./run-test.sh

  server:
    <<: *defaults
    working_directory: ~/build-root/server
    steps:
      - checkout: { path: ~/build-root }
      - attach_workspace: { at: ~/build-root }
      - run:
          name: Check whether server changed
          command: |
            if [ -e ci_meta/not_changed ]; then
              if [ -e ci_meta/success ]; then
                exit 0
              else
                exit 1
              fi
            else
              echo "run tests"
            fi

      - run:
          name: Install dependencies
          command: echo "install"

      - run:
          name: Build
          command: echo "Building Server"

      - run:
          name: Test
          command: ./run-test.sh

  docs:
    <<: *defaults
    working_directory: ~/build-root/docs
    steps:
      - checkout: { path: ~/build-root }
      - attach_workspace: { at: ~/build-root }
      - run:
          name: Check whether docs changed
          command: |
            if [ -e ci_meta/not_changed ]; then
              if [ -e ci_meta/success ]; then
                exit 0
              else
                exit 1
              fi
            else
              echo "run tests"
            fi

      - run:
          name: Install dependencies
          command: echo "install"

      - run:
          name: Build
          command: echo "Building docs"

      - run:
          name: Test
          command: ./run-test.sh

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - clone_and_hash
      - client:
          requires:
            - clone_and_hash
      - server:
          requires:
            - clone_and_hash
      - docs:
          requires:
            - clone_and_hash
