version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.2.1
  working_directory: ~/build-root

jobs:
  clone_and_hash:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-project-metadata-{{ .Branch }}
            - v1-project-metadata-master

      - run:
          name: Initialize metadata
          command: |
            touch {client,server,docs}/.commit-hash

      - run:
          name: Get latest commit of projects
          command: |
            git log --pretty=format:'%H' -n 1 -- client | tee client/.commit-hash.new
            git log --pretty=format:'%H' -n 1 -- server | tee server/.commit-hash.new
            git log --pretty=format:'%H' -n 1 -- docs | tee docs/.commit-hash.new

      - run:
          name: Determine changes
          command: |
            if ! diff client/.commit-hash{,.new} > /dev/null; then
              touch client/.changed
            fi

            if ! diff server/.commit-hash{,.new} > /dev/null; then
              touch server/.changed
            fi

            if ! diff docs/.commit-hash{,.new} > /dev/null; then
              touch docs/.changed
            fi

      - persist_to_workspace:
          root: .
          paths:
            - .

      - save_cache:
          key: v1-project-metadata-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - client/.commit-hash
            - server/.commit-hash
            - docs/.commit-hash

  client:
    <<: *defaults
    working_directory: ~/build-root/client
    steps:
      - checkout: { path: ~/build-root }
      - attach_workspace: { at: ~/build-root }
      - run:
          name: Check whether client changed
          command: |
            if [ -e .changed ]; then
              echo "let's do this"
            else
              echo "nothing to do"
            fi

      - run:
          name: Install dependencies
          command: echo "install"

      - run:
          name: Build
          command: echo "Building Client"

      - run:
          name: Test
          command: ./run-test.sh

  server:
    <<: *defaults
    working_directory: ~/build-root/server
    steps:
      - checkout: { path: ~/build-root }
      - attach_workspace: { at: ~/build-root }
      - run:
          name: Check whether server changed
          command: |
            if [ -e .changed ]; then
              echo "let's do this"
            else
              echo "nothing to do"
            fi

      - run:
          name: Install dependencies
          command: echo "install"

      - run:
          name: Build
          command: echo "Building Server"

      - run:
          name: Test
          command: ./run-test.sh

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - clone_and_hash
      - client:
          requires:
            - clone_and_hash
      - server:
          requires:
            - clone_and_hash
