version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.2.1
  working_directory: ~/build-root

jobs:
  clone_and_hash:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Initialize metadata
          command: |
            ./.circleci/find_changed_projects.py | tee -a $BASH_ENV

      - run:
          name: try out
          command: |
            echo $CLIENT_CHANGED
            echo $CLIENT_SUCCESS
            echo $DOCS_CHANGED
            echo $DOCS_SUCCESS
            echo $SERVER_CHANGED
            echo $SERVER_SUCCESS

  client:
    <<: *defaults
    working_directory: ~/build-root/client
    steps:
      - checkout: { path: ~/build-root }
      - attach_workspace: { at: ~/build-root }
      - run:
          name: Check whether client changed
          command: |
            if [ "$CLIENT_CHANGED"=1 ]; then
              echo "let's do this"
            else
              echo "nothing to do"
            fi

      - run:
          name: Install dependencies
          command: echo "install"

      - run:
          name: Build
          command: echo "Building Client"

      - run:
          name: Test
          command: ./run-test.sh

  server:
    <<: *defaults
    working_directory: ~/build-root/server
    steps:
      - checkout: { path: ~/build-root }
      - attach_workspace: { at: ~/build-root }
      - run:
          name: Check whether server changed
          command: |
            if [ "$SERVER_CHANGED"=1 ]; then
              echo "let's do this"
            else
              echo "nothing to do"
            fi

      - run:
          name: Install dependencies
          command: echo "install"

      - run:
          name: Build
          command: echo "Building Server"

      - run:
          name: Test
          command: ./run-test.sh

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - clone_and_hash
      - client:
          requires:
            - clone_and_hash
      - server:
          requires:
            - clone_and_hash
