version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.2.1
  working_directory: ~/build-root

jobs:
  clone_and_hash:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-project-metadata-{{ .Branch }}
            - v1-project-metadata-master

      - run:
          name: Initialize metadata
          command: |
            mkdir -p .project-metadata
            touch .client-hash .server-hash

      - run:
          name: Get latest commit of projects
          command: |
            git log --pretty=format:'%H' -n 1 -- client | tee .client-hash.new
            git log --pretty=format:'%H' -n 1 -- server | tee .server-hash.new

      - run:
          name: Determine changes
          command: |
            if ! diff .client-hash{,.new} > /dev/null; then
              touch .project-metadata/.client-changed
            fi

            if ! diff .server-hash{,.new} > /dev/null; then
              touch .project-metadata/.server-changed
            fi

      - run:
          name: Update last built commit of projects
          command: |
            mv .client-hash{.new,}
            mv .server-hash{.new,}

      - persist_to_workspace:
          root: .
          paths:
            - .project-metadata

      - save_cache:
          key: v1-project-metadata-{{ .Branch }}-{{ epoch }}
          paths:
            - .client-hash
            - .server-hash

  client:
    <<: *defaults
    working_directory: ~/build-root/client
    steps:
      - checkout: { path: ~/build-root }
      - attach_workspace: { at: . }
      - run:
          name: Check whether client changed
          command: |
            if [ -e .project-metadata/.client-changed ]; then
              echo "let's do this"
            else
              echo "nothing to do"
            fi

      - run:
          name: Install dependencies
          command: echo "install"

      - run:
          name: Build
          command: echo "Building Client"

      - run:
          name: Test
          command: ./run-test.sh

  server:
    <<: *defaults
    working_directory: ~/build-root/server
    steps:
      - checkout: { path: ~/build-root }
      - attach_workspace: { at: . }
      - run:
          name: Check whether server changed
          command: |
            if [ -e .project-metadata/.server-changed ]; then
              echo "let's do this"
            else
              echo "nothing to do"
            fi

      - run:
          name: Install dependencies
          command: echo "install"

      - run:
          name: Build
          command: echo "Building Server"

      - run:
          name: Test
          command: ./run-test.sh

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - clone_and_hash
      - client:
          requires:
            - clone_and_hash
      - server:
          requires:
            - clone_and_hash
